### ISSUE TITLE
Configuration: BlobStorage on development

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#52]
Is there any soft that could mock BlobStorage while developing MonitorizareVot locally?

Right now with default non-sense config settings I'm rightly getting an error:
```
Unhandled Exception: System.InvalidOperationException: The configuration is invalid. Creating the instance for type IFileService failed. The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. ---> SimpleInjector.ActivationException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials.UpdateKey(String keyValue, String keyName)
   at VotingIrregularities.Api.Services.BlobService.get_Credentials() in /app/src/VotingIrregularities.Api/Services/BlobService.cs:line 21
```

Depends on this setting:
```
    "BlobStorageOptions": {
        "Container": "TBR",
        "AccountName": "TBR",
        "AccountKey": "TBR"
    },
```

**Comment by KrzysztofMadejski** [comment]
VisualStudio has a simulator for that.
