### ISSUE TITLE
Error while sending note: Microsoft.WindowsAzure.Storage.StorageException: The account being accessed does not support http

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#92]
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
mv-api    |       An unhandled exception has occurred while executing the request.
mv-api    | Microsoft.WindowsAzure.Storage.StorageException: The account being accessed does not support http.
mv-api    |    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
mv-api    |    at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExistsAsync(BlobContainerPublicAccessType accessType, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
mv-api    |    at VotingIrregularities.Api.Services.BlobService.UploadFromStreamAsync(Stream sourceStream, String mimeType, String extension) in /app/src/VotingIrregularities.Api/Services/BlobService.cs:line 38
mv-api    |    at VotingIrregularities.Api.Queries.FileQueryHandler.Handle(ModelFile message) in /app/src/VotingIrregularities.Api/Queries/FileQueryHandler.cs:line 25
mv-api    |    at VotingIrregularities.Api.Controllers.Nota.Upload(IFormFile file, ModelNota nota) in /app/src/VotingIrregularities.Api/Controllers/Nota.cs:line 52
mv-api    |    at lambda_method(Closure , Object )
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
mv-api    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
mv-api    |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
mv-api    |    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
mv-api    |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
mv-api    |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
mv-api    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
mv-api    |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
mv-api    | Request Information
mv-api    | RequestID:89680e64-401e-0139-61bb-669c01000000
mv-api    | RequestDate:Thu, 18 Oct 2018 08:21:20 GMT
mv-api    | StatusMessage:The account being accessed does not support http.
mv-api    | ErrorCode:AccountRequiresHttps
mv-api    | ErrorMessage:The account being accessed does not support http.
mv-api    | RequestId:89680e64-401e-0139-61bb-669c01000000
mv-api    | Time:2018-10-18T08:21:20.4140202Z

```

**Comment by KrzysztofMadejski** [comment]
Because connection is hardcoded over http. Https [can be disabled](https://stackoverflow.com/questions/44528162/azure-storage-java-api-account-does-not-support-http) on Blob settings in Azure Portal, but best is to code setting to trigger https on/off.
